# Generated by Django 5.0.2 on 2025-03-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
