version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
    ports:
      - 5432:5432
    # volumes:
    #   - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "inpv"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal_network

  redis:
    image: redis:7
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
    networks:
      - internal_network

  mongodb:
    image: mongo:8
    volumes:
      - ./mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal_network

  migrations:
    build: .
    environment:
      SQL_ENGINE: ${SQL_ENGINE}
      SQL_DATABASE: ${SQL_DATABASE}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_HOST: ${SQL_HOST}
      SQL_PORT: ${SQL_PORT}
      DATABASE: ${DATABASE}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    volumes:
      - ./db/:/usr/src/db
      - ./src/:/usr/src/app
    command: >
      sh -c "
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py loaddata demo_data.json ;
             python manage.py loaddata users.json ;
             python /usr/src/db/migrations/migrate.py &&
             python manage.py createsuperuser --username admin --email admin@admin.com --noinput"
    depends_on:
      db:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - internal_network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80  # Bind only to localhost
    volumes:
      - ./src/:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock  # Mount the Docker socket
    ports:
      - 80:80
    env_file:
      - .env
    depends_on:
      migrations:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    networks:
      - internal_network


networks:
  internal_network:
    driver: bridge

