services:
  db:
    image: postgres:15-alpine
    deploy:
      resources:
        limits:
          cpus: "0.2"
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "inpv"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    deploy:
      resources:
        limits:
          cpus: "0.05"
    networks:
      - internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:8
    deploy:
      resources:
        limits:
          cpus: "0.5"
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - internal
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    build: .
    environment:
      SQL_ENGINE: ${SQL_ENGINE}
      SQL_DATABASE: ${SQL_DATABASE}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_HOST: ${SQL_HOST}
      SQL_PORT: ${SQL_PORT}
      DATABASE: ${DATABASE}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    volumes:
      - ./db/:/usr/src/db
      - ./src/:/usr/src/app
    networks:
      - internal
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py loaddata demo_data.json &&
             python manage.py loaddata users.json &&
             python /usr/src/db/migrations/migrate.py &&
             python manage.py createsuperuser --username admin --email admin@admin.com --noinput ;
             echo 0"
    depends_on:
      db:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: Dockerfile-prod
    volumes:
      - ./src/tmp/:/usr/src/app/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: "0.2"
    command: python -m gunicorn --bind 0.0.0.0:8000 --workers 1 inpv.wsgi:application
    env_file:
      - .env
    networks:
      - internal
    depends_on:
      migrations:
        condition: service_completed_successfully

  nginx:
    image: nginx:latest
    deploy:
      resources:
        limits:
          cpus: "0.15"
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/public/:/static:ro
    networks:
      - internal
    depends_on:
      - web

networks:
  internal:
    driver: bridge
