# stage 1
FROM python:3.11.4-slim-buster AS builder
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
RUN pip install --upgrade pip
COPY ./requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# stage 2
FROM python:3.11.4-slim-buster
RUN useradd -m -r appuser && \
   mkdir /usr/src/app && \
   chown -R appuser /usr/src/app
COPY --from=builder /usr/local/lib/python3.11/site-packages/ /usr/local/lib/python3.11/site-packages/
COPY --from=builder /usr/local/bin/ /usr/local/bin/
WORKDIR /usr/src/app
COPY --chown=appuser:appuser ./src .

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

EXPOSE 8000
