version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8888
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8888:8888
    env_file:
      - ./.env.local
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=interactive_tool

volumes:
  postgres_data:
