# Stage 1: Base build stage
FROM python:3.11.4-slim-buster AS builder

# Create the app directory
RUN mkdir -p /usr/src/app

# Set the working directory
WORKDIR /usr/src/app

# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install dependencies first for caching benefit
RUN pip install --upgrade pip
COPY ./requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Stage 2: Production stage
FROM python:3.11.4-slim-buster

RUN useradd -m -r appuser && \
   mkdir /usr/src/app && \
   chown -R appuser /usr/src/app

# Copy the Python dependencies from the builder stage
COPY --from=builder /usr/local/lib/python3.11/site-packages/ /usr/local/lib/python3.11/site-packages/
COPY --from=builder /usr/local/bin/ /usr/local/bin/

# Set the working directory
WORKDIR /usr/src/app

COPY --chown=appuser:appuser ./src .

# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Switch to non-root user
USER appuser

# Expose the application port
EXPOSE 8000

# Make entry file executable
# RUN chmod +x  /app/entrypoint.prod.sh

# Start the application using Gunicorn
# CMD ["/app/entrypoint.prod.sh"]
