# Generated by Django 5.0.2 on 2025-03-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker_1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="completion_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="habit",
            name="date_completed",
            field=models.DateField(blank=True, null=True),
        ),
    ]
