# Generated by Django 5.0.2 on 2025-04-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('test_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('selected_answers', models.JSONField()),
                ('correct_answers', models.JSONField()),
                ('is_correct', models.BooleanField()),
                ('points_earned', models.IntegerField()),
                ('attempt_number', models.IntegerField()),
                ('submitted', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id'], name='tests_testr_user_id_f3d3d4_idx'), models.Index(fields=['test_id'], name='tests_testr_test_id_01a254_idx'), models.Index(fields=['question_id'], name='tests_testr_questio_a10e1d_idx'), models.Index(fields=['attempt_number'], name='tests_testr_attempt_85cea3_idx'), models.Index(fields=['submitted'], name='tests_testr_submitt_f5575e_idx')],
                'unique_together': {('user_id', 'test_id', 'question_id', 'attempt_number')},
            },
        ),
    ]
