# Generated by Django 5.0.2 on 2025-04-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_testresult_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='is_partially_correct',
            field=models.BooleanField(default=False),
        ),
    ]
