# Generated by Django 5.0.2 on 2025-03-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthday',
            name='email',
        ),
    ]
