# Generated by Django 5.0.2 on 2025-03-14 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0002_remove_birthday_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthday',
            options={'ordering': ['birth_date'], 'verbose_name_plural': 'Birthdays'},
        ),
        migrations.AlterUniqueTogether(
            name='birthday',
            unique_together={('name', 'birth_date')},
        ),
    ]
