# Generated by Django 5.0.2 on 2025-03-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0003_alter_birthday_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='calendar_name',
            field=models.CharField(default='Default', max_length=100),
        ),
    ]
