# Generated by Django 5.0.2 on 2025-03-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0004_birthday_calendar_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='calendar_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
