# Generated by Django 5.0.2 on 2025-03-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='Category',
			fields=[
				('id', models.AutoField(primary_key=True, serialize=False)),
				('name', models.CharField(max_length=100, unique=True)),
			],
		),
		migrations.CreateModel(
			name='Habit',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=200)),
				('completed', models.BooleanField(default=False)),
				('date_completed', models.DateField(blank=True, null=True)),
				('completion_count', models.PositiveIntegerField(default=0)),
			],
		),
		migrations.CreateModel(
			name='Post',
			fields=[
				('id', models.AutoField(primary_key=True, serialize=False)),
				('title', models.CharField(max_length=200)),
				('content', models.TextField()),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('categories', models.ManyToManyField(related_name='posts', to='demos.category')),
			],
		),
	]
