# Generated by Django 5.0.2 on 2025-03-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		('demos', '0001_initial'),
	]

	operations = [
		migrations.RemoveField(
			model_name='post',
			name='categories',
		),
		migrations.DeleteModel(
			name='Habit',
		),
		migrations.DeleteModel(
			name='Category',
		),
		migrations.DeleteModel(
			name='Post',
		),
	]
